apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: japersa/backend-nodejs-api:latest
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
          - name: MONGO_HOST
            value: "mongodb"
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MONGO_USER
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MONGO_PASSWORD
          - name: PG_HOST
            value: "postgres"
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_DATABASE
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_USER
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-demo
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP